site_name: CPN IDE User Guide

use_directory_urls: false

extra_css: [css/bootstrap-3.3.7.min.css, css/extra.css]

nav:
  - Home: index.md
  - About: about.md
  
# theme:
#     name: null
#     custom_dir: 'custom_theme'
